// PITCHVAULT FIFA 22 Career Archive - Exact Verified Data
// Source: FIFA 22 Career Summary Screenshots
// Player: Sakai Sree
// Position: ST
// Current Club: Manchester United
// Current OVR: 91

export const FIFA_PLAYER_DATA = {
  name: 'Sakai Sree',
  position: 'ST',
  nationality: 'New Zealand',
  current_ovr: 91,
  current_club: 'Manchester United',
  energy: 100,
  form: 8.7,
  rank: 1,
  injury_status: 'Healthy',
  suspension_status: 'No Suspensions',
}

export const FIFA_CAREER_OVERVIEW = {
  player: 'Sakai Sree',
  ovr: 91,
  position: 'ST',
  clubs_count: 3,
  league_titles: 4,
  domestic_cups_won: 5,
  continental_cups_won: 3,
  current_wage: '€145,000 per week',
  current_value: '€187,000,000',
  team_of_the_week: 17,
  player_of_the_month: 3,
  player_of_the_year: 0,
  career_stats: {
    appearances: 223,
    wins: 185,
    draws: 31,
    losses: 7,
    goals: 517,
    assists: 167,
    yellow_cards: 11,
    red_cards: 1,
  },
}

export const FIFA_SEASONS = [
  {
    // 2021/22 - AS SAINT-ÉTIENNE
    season_name: '2021/2022',
    start_year: 2021,
    end_year: 2022,
    club: 'AS SAINT-ÉTIENNE',
    position: 'ST',
    league: 'Ligue 1 Uber Eats',
    league_position: '3rd',
    average_rating: 8.3,
    league_result: 'League',
    coupe_nationale_result: 'Winner',
    trophee_champ_result: 'Final',
    man_of_the_match: 21,
    team_of_the_week: 15,
    player_of_the_month: 6,
    player_of_the_year: false,
    stats: {
      appearances: 45,
      wins: 37,
      draws: 6,
      losses: 2,
      goals: 127,
      assists: 40,
      yellow_cards: 5,
      red_cards: 0,
    },
    source: 'FIFA 22 Career Summary screenshot',
    verified: true,
  },
  {
    // 2022/23 - AS SAINT-ÉTIENNE
    season_name: '2022/2023',
    start_year: 2022,
    end_year: 2023,
    club: 'AS SAINT-ÉTIENNE',
    position: 'ST',
    league: 'Ligue 1 Uber Eats',
    league_position: '1st',
    average_rating: 9.1,
    league_result: 'Winner',
    uEFA_champions_league_result: 'Winner',
    coupe_nationale_result: 'Winner',
    man_of_the_match: 33,
    team_of_the_week: 12,
    player_of_the_month: 3,
    player_of_the_year: false,
    stats: {
      appearances: 59,
      wins: 46,
      draws: 10,
      losses: 3,
      goals: 192,
      assists: 63,
      yellow_cards: 3,
      red_cards: 1,
    },
    source: 'FIFA 22 Career Summary screenshot',
    verified: true,
  },
  {
    // 2023/24 - FC BARCELONA
    season_name: '2023/2024',
    start_year: 2023,
    end_year: 2024,
    club: 'FC BARCELONA',
    position: 'ST',
    league: 'LaLiga Santander',
    league_position: '1st',
    average_rating: 8.8,
    league_result: 'Winner',
    uEFA_champions_league_result: 'Winner',
    copa_de_espana_result: 'Winner',
    man_of_the_match: 26,
    team_of_the_week: 16,
    player_of_the_month: 6,
    player_of_the_year: false,
    stats: {
      appearances: 55,
      wins: 51,
      draws: 4,
      losses: 0,
      goals: 177,
      assists: 53,
      yellow_cards: 1,
      red_cards: 0,
    },
    source: 'FIFA 22 Career Summary screenshot',
    verified: true,
  },
  {
    // 2024/25 - MANCHESTER UNITED
    season_name: '2024/2025',
    start_year: 2024,
    end_year: 2025,
    club: 'MANCHESTER UNITED',
    position: 'ST',
    league: 'Premier League',
    league_position: '1st',
    average_rating: 9.0,
    league_result: 'Winner',
    uEFA_champions_league_result: 'Winner',
    carabao_cup_result: 'Winner',
    emirates_fa_cup_result: 'Winner',
    man_of_the_match: 32,
    team_of_the_week: 17,
    player_of_the_month: 3,
    player_of_the_year: false,
    stats: {
      // Note: Screenshot cuts off final stats - leave empty
      appearances: null,
      wins: null,
      draws: null,
      losses: null,
      goals: null,
      assists: null,
      yellow_cards: null,
      red_cards: null,
    },
    source: 'FIFA 22 Career Summary screenshot (partial)',
    verified: false,
    note: 'Final stats row not visible in screenshot - awaiting user verification',
  },
]

export const FIFA_CLUBS = [
  {
    name: 'AS SAINT-ÉTIENNE',
    short_name: 'ASSE',
    country: 'France',
    league: 'Ligue 1 Uber Eats',
    seasons: ['2021/22', '2022/23'],
    trophies: ['Coupe Nationale', 'Trophée Champ Final'],
  },
  {
    name: 'FC BARCELONA',
    short_name: 'FCB',
    country: 'Spain',
    league: 'LaLiga Santander',
    seasons: ['2023/24'],
    trophies: ['LaLiga', 'Copa de España', 'UEFA Champions League'],
  },
  {
    name: 'MANCHESTER UNITED',
    short_name: 'MU',
    country: 'England',
    league: 'Premier League',
    seasons: ['2024/25'],
    trophies: ['Premier League', 'UEFA Champions League', 'Carabao Cup', 'Emirates FA Cup'],
  },
]

export const FIFA_TRANSFERS = [
  {
    from_club: 'AS SAINT-ÉTIENNE',
    to_club: 'FC BARCELONA',
    transfer_fee: '€150,000,000',
    season: '2023',
    note: 'Summer 2023 transfer',
  },
  {
    from_club: 'FC BARCELONA',
    to_club: 'MANCHESTER UNITED',
    transfer_fee: '€300,000,000',
    season: '2024',
    note: 'Summer 2024 transfer - Record fee',
  },
]

export const FIFA_INTERNATIONAL_CAREER = {
  country: 'New Zealand',
  world_cup_2022: {
    tournament: 'FIFA World Cup',
    year: 2022,
    result: 'Winner',
    final_opponent: 'France',
    final_score: '7-2',
    player_of_tournament: true,
    goals_in_final: 7,
    note: '7-goal performance against France',
  },
}

export const FIFA_TROPHIES = [
  { competition: 'Coupe Nationale', season: '2021/22', club: 'AS SAINT-ÉTIENNE', winner: true },
  { competition: 'Trophée Champ', season: '2021/22', club: 'AS SAINT-ÉTIENNE', runner_up: true },
  { competition: 'UEFA Champions League', season: '2022/23', club: 'AS SAINT-ÉTIENNE', winner: true },
  { competition: 'Ligue 1', season: '2022/23', club: 'AS SAINT-ÉTIENNE', winner: true },
  { competition: 'Coupe Nationale', season: '2022/23', club: 'AS SAINT-ÉTIENNE', winner: true },
  { competition: 'LaLiga Santander', season: '2023/24', club: 'FC BARCELONA', winner: true },
  { competition: 'Copa de España', season: '2023/24', club: 'FC BARCELONA', winner: true },
  { competition: 'UEFA Champions League', season: '2023/24', club: 'FC BARCELONA', winner: true },
  { competition: 'Premier League', season: '2024/25', club: 'MANCHESTER UNITED', winner: true },
  { competition: 'UEFA Champions League', season: '2024/25', club: 'MANCHESTER UNITED', winner: true },
  { competition: 'Carabao Cup', season: '2024/25', club: 'MANCHESTER UNITED', winner: true },
  { competition: 'Emirates FA Cup', season: '2024/25', club: 'MANCHESTER UNITED', winner: true },
  { competition: 'FIFA World Cup', season: '2022', club: 'New Zealand', winner: true, international: true },
]

export const FIFA_CAREER_SUMMARY_2021_22 = {
  season: '2021/2022',
  club: 'AS SAINT-ÉTIENNE',
  position: 'ST',
  overall_rating: 8.3,
  energy: 100,
  form: 8.3,
  rank: 3,
  injury_status: 'Healthy',
  suspension_status: 'No Suspensions',
  role: 'Starter',
  league_position: '3rd in Ligue 1 Uber Eats',
  average_rating: 8.3,
  competitions: {
    ligue_1_uber_eats: 'League',
    coupe_nationale: 'Winner',
    trophee_champ: 'Final',
  },
  individual_awards: {
    man_of_the_match: 21,
    team_of_the_week: 15,
    player_of_the_month: 6,
    player_of_the_year: false,
  },
  stats: {
    appearances: 45,
    wins: 37,
    draws: 6,
    losses: 2,
    goals: 127,
    assists: 40,
    yellow_cards: 5,
    red_cards: 0,
  },
}

export const FIFA_CAREER_SUMMARY_2022_23 = {
  season: '2022/2023',
  club: 'AS SAINT-ÉTIENNE',
  position: 'ST',
  overall_rating: 9.1,
  energy: 100,
  form: 9.1,
  rank: 1,
  injury_status: 'Healthy',
  suspension_status: 'No Suspensions',
  role: 'Starter',
  league_position: '1st in Ligue 1 Uber Eats',
  average_rating: 9.1,
  competitions: {
    ligue_1_uber_eats: 'Winner',
    uEFA_champions_league: 'Winner',
    coupe_nationale: 'Winner',
  },
  individual_awards: {
    man_of_the_match: 33,
    team_of_the_week: 12,
    player_of_the_month: 3,
    player_of_the_year: false,
  },
  stats: {
    appearances: 59,
    wins: 46,
    draws: 10,
    losses: 3,
    goals: 192,
    assists: 63,
    yellow_cards: 3,
    red_cards: 1,
  },
}

export const FIFA_CAREER_SUMMARY_2023_24 = {
  season: '2023/2024',
  club: 'FC BARCELONA',
  position: 'ST',
  overall_rating: 8.8,
  energy: 100,
  form: 8.8,
  rank: 1,
  injury_status: 'Healthy',
  suspension_status: 'No Suspensions',
  role: 'Starter',
  league_position: '1st in LaLiga Santander',
  average_rating: 8.8,
  competitions: {
    laliga_santander: 'Winner',
    uEFA_champions_league: 'Winner',
    copa_de_espana: 'Winner',
  },
  individual_awards: {
    man_of_the_match: 26,
    team_of_the_week: 16,
    player_of_the_month: 6,
    player_of_the_year: false,
  },
  stats: {
    appearances: 55,
    wins: 51,
    draws: 4,
    losses: 0,
    goals: 177,
    assists: 53,
    yellow_cards: 1,
    red_cards: 0,
  },
}

export const FIFA_CAREER_SUMMARY_2024_25 = {
  season: '2024/2025',
  club: 'MANCHESTER UNITED',
  position: 'ST',
  overall_rating: 9.0,
  energy: 100,
  form: 8.7,
  rank: 1,
  injury_status: 'Healthy',
  suspension_status: 'No Suspensions',
  role: 'Starter',
  league_position: '1st in Premier League',
  average_rating: 9.0,
  competitions: {
    premier_league: 'Winner',
    uEFA_champions_league: 'Winner',
    carabao_cup: 'Winner',
    emirates_fa_cup: 'Winner',
  },
  individual_awards: {
    man_of_the_match: 32,
    team_of_the_week: 17,
    player_of_the_month: 3,
    player_of_the_year: false,
  },
  stats: {
    // Note: Final stat row not visible in screenshot
    appearances: null,
    wins: null,
    draws: null,
    losses: null,
    goals: null,
    assists: null,
    yellow_cards: null,
    red_cards: null,
  },
  note: 'Screenshot cuts off final numerical stats row',
}

export const FIFA_ATTRIBUTES = {
  overall: 91,
  pace: 93,
  shooting: 93,
  passing: 54,
  dribbling: 85,
  defending: 33,
  physical: 80,
  level: 25,
}

export const FIFA_ARCHETYPES = ['Finisher', 'Bull', 'Cheetah', 'Lynx']
