import { v4 as uuidv4 } from 'uuid'

export const SEED_DATA = {
  clubs: [
    {
      id: 'club-1',
      name: 'AS Saint-Étienne',
      short_name: 'ASSE',
      country: 'France',
      league: 'Ligue 1',
      logo_url: null,
      primary_color: '#00AA00',
      secondary_color: '#FFFFFF',
    },
    {
      id: 'club-2',
      name: 'FC Barcelona',
      short_name: 'FCB',
      country: 'Spain',
      league: 'La Liga',
      logo_url: null,
      primary_color: '#004B87',
      secondary_color: '#DC143C',
    },
    {
      id: 'club-3',
      name: 'Manchester United',
      short_name: 'MAN UTD',
      country: 'England',
      league: 'Premier League',
      logo_url: null,
      primary_color: '#DA291C',
      secondary_color: '#FFF044',
    },
  ],
  competitions: [
    {
      id: 'comp-1',
      name: 'Ligue 1',
      country: 'France',
      competition_type: 'league',
      logo_url: null,
    },
    {
      id: 'comp-2',
      name: 'La Liga',
      country: 'Spain',
      competition_type: 'league',
      logo_url: null,
    },
    {
      id: 'comp-3',
      name: 'Premier League',
      country: 'England',
      competition_type: 'league',
      logo_url: null,
    },
    {
      id: 'comp-4',
      name: 'UEFA Champions League',
      country: null,
      competition_type: 'european',
      logo_url: null,
    },
    {
      id: 'comp-5',
      name: 'Copa del Rey',
      country: 'Spain',
      competition_type: 'cup',
      logo_url: null,
    },
    {
      id: 'comp-6',
      name: 'FIFA World Cup',
      country: null,
      competition_type: 'international',
      logo_url: null,
    },
  ],
  archetypes: [
    { id: 'arch-1', name: 'FINISHER', description: 'Elite goal scorer', category: 'attacking' },
    { id: 'arch-2', name: 'BULL', description: 'Physical striker', category: 'attacking' },
    { id: 'arch-3', name: 'CHEETAH', description: 'Pace and agility', category: 'attacking' },
    { id: 'arch-4', name: 'LYNX', description: 'Intelligent forward', category: 'attacking' },
  ],
  careers: [
    {
      id: 'career-1',
      user_id: 'user-1', // Will be replaced with actual user
      name: 'Sakai Sree FIFA 22 Career',
      game_version: 'FIFA 22',
      description: 'The complete journey from Saint-Étienne to Manchester United. World Cup champion 2022.',
      status: 'active' as const,
    },
  ],
  players: [
    {
      id: 'player-1',
      career_id: 'career-1',
      name: 'Sakai Sree',
      short_name: 'S. Sree',
      position: 'ST',
      nationality: 'New Zealand',
      date_of_birth: '2005-06-15',
      age: 20,
      preferred_foot: 'right' as const,
      jersey_number: 9,
      height: 185,
      weight: 82,
      current_ovr: 91,
      current_level: 25,
      current_club_id: 'club-3',
    },
  ],
  seasons: [
    {
      id: 'season-1',
      career_id: 'career-1',
      name: '2022/23',
      start_year: 2022,
      end_year: 2023,
      current_club_id: 'club-1',
      appearances: 36,
      goals: 42,
      assists: 16,
      average_rating: 8.1,
      wins: 24,
      draws: 6,
      losses: 6,
    },
    {
      id: 'season-2',
      career_id: 'career-1',
      name: '2023/24',
      start_year: 2023,
      end_year: 2024,
      current_club_id: 'club-2',
      appearances: 49,
      goals: 91,
      assists: 34,
      average_rating: 8.4,
      wins: 38,
      draws: 8,
      losses: 3,
    },
    {
      id: 'season-3',
      career_id: 'career-1',
      name: '2024/25',
      start_year: 2024,
      end_year: 2025,
      current_club_id: 'club-2',
      appearances: 57,
      goals: 176,
      assists: 80,
      average_rating: 8.7,
      wins: 48,
      draws: 7,
      losses: 2,
    },
    {
      id: 'season-4',
      career_id: 'career-1',
      name: '2025/26',
      start_year: 2025,
      end_year: 2026,
      current_club_id: 'club-3',
      appearances: 18,
      goals: 64,
      assists: 22,
      average_rating: 8.9,
      wins: 14,
      draws: 3,
      losses: 1,
    },
  ],
  matches: [
    // World Cup Final (recent)
    {
      id: 'match-1',
      career_id: 'career-1',
      season_id: 'season-4',
      club_id: 'club-3', // New Zealand doesn't have club, using placeholder
      competition_id: 'comp-6',
      date: '2022-07-17T20:00:00Z',
      opponent: 'France',
      opponent_logo_url: null,
      home_away: 'away' as const,
      player_team_score: 7,
      opponent_score: 2,
      result: 'win' as const,
      player_rating: 10.0,
      goals: 7,
      assists: 1,
      minutes_played: 90,
      is_motm: true,
      notes: 'World Cup Final. Player of the Tournament.',
    },
    // Recent Manchester United matches
    {
      id: 'match-2',
      career_id: 'career-1',
      season_id: 'season-4',
      club_id: 'club-3',
      competition_id: 'comp-3',
      date: '2026-01-10T15:00:00Z',
      opponent: 'Liverpool',
      opponent_logo_url: null,
      home_away: 'home' as const,
      player_team_score: 3,
      opponent_score: 2,
      result: 'win' as const,
      player_rating: 9.1,
      goals: 2,
      assists: 1,
      minutes_played: 89,
      is_motm: true,
      notes: 'Derby victory.',
    },
    {
      id: 'match-3',
      career_id: 'career-1',
      season_id: 'season-4',
      club_id: 'club-3',
      competition_id: 'comp-3',
      date: '2026-01-05T12:30:00Z',
      opponent: 'Arsenal',
      opponent_logo_url: null,
      home_away: 'away' as const,
      player_team_score: 2,
      opponent_score: 1,
      result: 'win' as const,
      player_rating: 8.7,
      goals: 1,
      assists: 1,
      minutes_played: 87,
      is_motm: false,
      notes: null,
    },
    {
      id: 'match-4',
      career_id: 'career-1',
      season_id: 'season-4',
      club_id: 'club-3',
      competition_id: 'comp-3',
      date: '2025-12-29T19:45:00Z',
      opponent: 'Chelsea',
      opponent_logo_url: null,
      home_away: 'home' as const,
      player_team_score: 4,
      opponent_score: 1,
      result: 'win' as const,
      player_rating: 9.3,
      goals: 2,
      assists: 0,
      minutes_played: 90,
      is_motm: true,
      notes: 'Brilliant performance.',
    },
  ],
  transfers: [
    {
      id: 'transfer-1',
      career_id: 'career-1',
      player_id: 'player-1',
      from_club_id: 'club-1',
      to_club_id: 'club-2',
      transfer_date: '2023-07-01T00:00:00Z',
      season_id: 'season-2',
      transfer_fee: 85000000,
      currency: 'EUR',
      transfer_type: 'permanent' as const,
      notes: 'Breakthrough transfer to Barcelona.',
    },
    {
      id: 'transfer-2',
      career_id: 'career-1',
      player_id: 'player-1',
      from_club_id: 'club-2',
      to_club_id: 'club-3',
      transfer_date: '2025-07-15T00:00:00Z',
      season_id: 'season-4',
      transfer_fee: 300000000,
      currency: 'EUR',
      transfer_type: 'permanent' as const,
      notes: 'Record transfer to Manchester United. Biggest move in career mode history.',
    },
  ],
  trophies: [
    {
      id: 'trophy-1',
      career_id: 'career-1',
      competition_id: 'comp-6',
      season_id: null,
      club_id: 'club-3', // New Zealand representation
      country: 'New Zealand',
      winner: true,
      date: '2022-07-17T00:00:00Z',
      notes: 'FIFA World Cup 2022 Champion',
    },
    {
      id: 'trophy-2',
      career_id: 'career-1',
      competition_id: 'comp-4',
      season_id: 'season-3',
      club_id: 'club-2',
      country: null,
      winner: true,
      date: '2024-05-31T00:00:00Z',
      notes: 'UEFA Champions League',
    },
    {
      id: 'trophy-3',
      career_id: 'career-1',
      competition_id: 'comp-2',
      season_id: 'season-3',
      club_id: 'club-2',
      country: null,
      winner: true,
      date: '2024-06-01T00:00:00Z',
      notes: 'La Liga',
    },
    {
      id: 'trophy-4',
      career_id: 'career-1',
      competition_id: 'comp-5',
      season_id: 'season-3',
      club_id: 'club-2',
      country: null,
      winner: true,
      date: '2024-05-25T00:00:00Z',
      notes: 'Copa del Rey',
    },
  ],
  awards: [
    {
      id: 'award-1',
      career_id: 'career-1',
      name: 'Player of the Tournament',
      season_id: null,
      competition_id: 'comp-6',
      date: '2022-07-17T00:00:00Z',
      category: 'Player of Tournament',
      description: 'FIFA World Cup 2022',
    },
    {
      id: 'award-2',
      career_id: 'career-1',
      name: 'European Golden Boot',
      season_id: 'season-3',
      competition_id: 'comp-4',
      date: '2024-05-31T00:00:00Z',
      category: 'Golden Boot',
      description: 'UEFA Champions League 2023/24',
    },
  ],
  attributeSnapshots: [
    {
      id: 'attr-1',
      career_id: 'career-1',
      player_id: 'player-1',
      date: '2022-09-01T00:00:00Z',
      season_id: 'season-1',
      overall: 78,
      pace: 87,
      shooting: 81,
      passing: 68,
      dribbling: 82,
      defending: 35,
      physical: 79,
      level: 6,
      skill_points: 12,
    },
    {
      id: 'attr-2',
      career_id: 'career-1',
      player_id: 'player-1',
      date: '2023-09-01T00:00:00Z',
      season_id: 'season-2',
      overall: 84,
      pace: 89,
      shooting: 87,
      passing: 62,
      dribbling: 84,
      defending: 32,
      physical: 81,
      level: 12,
      skill_points: 24,
    },
    {
      id: 'attr-3',
      career_id: 'career-1',
      player_id: 'player-1',
      date: '2024-09-01T00:00:00Z',
      season_id: 'season-3',
      overall: 89,
      pace: 91,
      shooting: 93,
      passing: 54,
      dribbling: 85,
      defending: 33,
      physical: 80,
      level: 18,
      skill_points: 36,
    },
    {
      id: 'attr-4',
      career_id: 'career-1',
      player_id: 'player-1',
      date: '2025-12-01T00:00:00Z',
      season_id: 'season-4',
      overall: 91,
      pace: 93,
      shooting: 93,
      passing: 54,
      dribbling: 85,
      defending: 33,
      physical: 80,
      level: 25,
      skill_points: 50,
    },
  ],
  timelineEvents: [
    {
      id: 'timeline-1',
      career_id: 'career-1',
      date: '2022-07-17T00:00:00Z',
      season_id: null,
      type: 'INTERNATIONAL',
      title: 'New Zealand win FIFA World Cup',
      description: 'Seven goals against France. Player of the Tournament. A legacy is born.',
      club_id: null,
      competition_id: 'comp-6',
      importance: 'legendary' as const,
      media_id: null,
    },
    {
      id: 'timeline-2',
      career_id: 'career-1',
      date: '2023-07-01T00:00:00Z',
      season_id: 'season-2',
      type: 'TRANSFER',
      title: 'AS Saint-Étienne → FC Barcelona',
      description: 'Breakthrough transfer to one of Europe\'s biggest clubs.',
      club_id: 'club-2',
      competition_id: null,
      importance: 'high' as const,
      media_id: null,
    },
    {
      id: 'timeline-3',
      career_id: 'career-1',
      date: '2024-05-31T00:00:00Z',
      season_id: 'season-3',
      type: 'TROPHY',
      title: 'Barcelona lift the UEFA Champions League',
      description: 'Sree delivers on the biggest stage as Barcelona claim European glory.',
      club_id: 'club-2',
      competition_id: 'comp-4',
      importance: 'legendary' as const,
      media_id: null,
    },
    {
      id: 'timeline-4',
      career_id: 'career-1',
      date: '2025-07-15T00:00:00Z',
      season_id: 'season-4',
      type: 'TRANSFER',
      title: 'Manchester United complete €300M transfer',
      description: 'The biggest move in career mode history. A new chapter begins at Old Trafford.',
      club_id: 'club-3',
      competition_id: null,
      importance: 'legendary' as const,
      media_id: null,
    },
  ],
  news: [
    {
      id: 'news-1',
      career_id: 'career-1',
      date: '2025-07-15T00:00:00Z',
      headline: 'Manchester United complete €300M transfer for Sakai Sree',
      subheadline: 'The biggest move in career mode history',
      body: 'A new chapter begins at Old Trafford as Sree joins Manchester United in a record transfer.',
      category: 'TRANSFER',
      image_url: null,
      club_id: 'club-3',
      competition_id: null,
      timeline_event_id: 'timeline-4',
    },
    {
      id: 'news-2',
      career_id: 'career-1',
      date: '2024-05-31T00:00:00Z',
      headline: 'Barcelona win UEFA Champions League',
      subheadline: 'Sree delivers on the biggest stage',
      body: 'Barcelona lift the European crown with Sree in spectacular form.',
      category: 'TROPHY',
      image_url: null,
      club_id: 'club-2',
      competition_id: 'comp-4',
      timeline_event_id: 'timeline-3',
    },
    {
      id: 'news-3',
      career_id: 'career-1',
      date: '2022-07-17T00:00:00Z',
      headline: 'New Zealand win the FIFA World Cup',
      subheadline: 'Sakai Sree named Player of the Tournament',
      body: 'Seven goals against France. Player of the Tournament. A legacy is born.',
      category: 'INTERNATIONAL',
      image_url: null,
      club_id: null,
      competition_id: 'comp-6',
      timeline_event_id: 'timeline-1',
    },
  ],
  playerArchetypes: [
    { id: 'pa-1', player_id: 'player-1', archetype_id: 'arch-1', status: 'unlocked' as const, unlocked_at: '2022-09-01T00:00:00Z' },
    { id: 'pa-2', player_id: 'player-1', archetype_id: 'arch-2', status: 'unlocked' as const, unlocked_at: '2023-01-15T00:00:00Z' },
    { id: 'pa-3', player_id: 'player-1', archetype_id: 'arch-3', status: 'unlocked' as const, unlocked_at: '2023-06-01T00:00:00Z' },
    { id: 'pa-4', player_id: 'player-1', archetype_id: 'arch-4', status: 'unlocked' as const, unlocked_at: '2024-03-20T00:00:00Z' },
  ],
}
