'use client'

import { ArrowUpRight, CalendarDays, Crown, Globe2, Layers3, Shield, Trophy, UserRound, Zap } from 'lucide-react'

const pageData: Record<string, { eyebrow: string; title: string; intro: string; icon: typeof UserRound; stats: [string, string][]; rows: [string, string, string][] }> = {
  CAREER: { eyebrow: 'PLAYER CAREER', title: 'THE COMPLETE JOURNEY', intro: 'A single view of every chapter, decision and defining performance in Sakai Sree’s career.', icon: UserRound, stats: [['CURRENT CLUB', 'Manchester United'], ['CAREER SPAN', '2022—26'], ['TOTAL APPEARANCES', '142'], ['CAREER GOALS', '373']], rows: [['2025/26', 'Manchester United', '91 OVR · 64 G · 22 A'], ['2024/25', 'FC Barcelona', '89 OVR · 176 G · 80 A'], ['2023/24', 'FC Barcelona', '84 OVR · 91 G · 34 A'], ['2022/23', 'AS Saint-Étienne', '78 OVR · 42 G · 16 A']] },
  SEASONS: { eyebrow: 'SEASON INDEX', title: 'EVERY SEASON, ON RECORD', intro: 'Compare output, growth and silverware across every completed campaign.', icon: CalendarDays, stats: [['SEASONS PLAYED', '4'], ['BEST OUTPUT', '176 GOALS'], ['BEST RATING', '8.9'], ['TROPHIES', '12']], rows: [['2025/26', 'Manchester United', '18 APP · 64 G · 22 A · 8.9'], ['2024/25', 'FC Barcelona', '57 APP · 176 G · 80 A · 8.7'], ['2023/24', 'FC Barcelona', '49 APP · 91 G · 34 A · 8.4'], ['2022/23', 'AS Saint-Étienne', '36 APP · 42 G · 16 A · 8.1']] },
  MATCHES: { eyebrow: 'MATCH CENTER', title: 'THE MATCH LOG', intro: 'A searchable record of the moments that moved the season forward.', icon: Shield, stats: [['MATCHES LOGGED', '160'], ['WINS', '56'], ['GOALS', '373'], ['MOTM AWARDS', '38']], rows: [['17 JUL', 'New Zealand vs France', 'W 7—2 · 10.0 · 7 G / 1 A'], ['12 MAY', 'Manchester United vs Arsenal', 'W 4—1 · 9.4 · 2 G / 1 A'], ['04 MAY', 'Manchester United vs Liverpool', 'D 2—2 · 8.1 · 1 G / 0 A'], ['28 APR', 'Manchester United vs Chelsea', 'W 3—0 · 9.0 · 2 G / 0 A']] },
  TRANSFERS: { eyebrow: 'TRANSFER LEDGER', title: 'EVERY MOVE MATTERS', intro: 'The economics and ambition behind each change of shirt.', icon: ArrowUpRight, stats: [['TOTAL SPEND', '€300M'], ['TRANSFERS', '3'], ['RECORD FEE', '€300M'], ['CURRENT VALUE', '€350M']], rows: [['2025', 'FC Barcelona → Manchester United', '€300M · COMPLETED'], ['2023', 'AS Saint-Étienne → FC Barcelona', '€85M · COMPLETED'], ['2022', 'Youth Academy → AS Saint-Étienne', 'FREE · PROMOTION']] },
  CLUBS: { eyebrow: 'CLUB INDEX', title: 'THE CLUB CHAPTERS', intro: 'Three clubs. Four seasons. One uninterrupted rise.', icon: Layers3, stats: [['CLUBS', '3'], ['LEAGUES', '3'], ['GOALS', '373'], ['HONOURS', '11']], rows: [['MANCHESTER UNITED', 'Premier League', '2025—26 · CURRENT'], ['FC BARCELONA', 'La Liga', '2023—25 · 267 GOALS'], ['AS SAINT-ÉTIENNE', 'Ligue 1', '2022—23 · 42 GOALS']] },
  INTERNATIONAL: { eyebrow: 'INTERNATIONAL CAREER', title: 'NEW ZEALAND, FOREVER', intro: 'The national team story, from first call-up to World Cup champion.', icon: Globe2, stats: [['CAPS', '32'], ['GOALS', '44'], ['WORLD CUPS', '1'], ['BEST FINISH', 'CHAMPIONS']], rows: [['2022', 'FIFA World Cup', 'CHAMPIONS · 7 GOALS IN FINAL'], ['2023', 'International Friendlies', '8 CAPS · 12 GOALS'], ['2024', 'World Cup Qualifiers', '6 CAPS · 9 GOALS']] },
  TROPHIES: { eyebrow: 'THE CABINET', title: 'A CAREER IN SILVERWARE', intro: 'Every final, every medal and every chapter that ended in celebration.', icon: Trophy, stats: [['TOTAL HONOURS', '12'], ['EUROPEAN CUPS', '1'], ['LEAGUE TITLES', '3'], ['WORLD CUPS', '1']], rows: [['2022', 'FIFA WORLD CUP', 'NEW ZEALAND · CHAMPIONS'], ['2024', 'UEFA CHAMPIONS LEAGUE', 'FC BARCELONA · CHAMPIONS'], ['2024', 'LA LIGA', 'FC BARCELONA · CHAMPIONS'], ['2025', 'PREMIER LEAGUE', 'MANCHESTER UNITED · IN PROGRESS']] },
  AWARDS: { eyebrow: 'INDIVIDUAL HONOURS', title: 'RECOGNITION, RECORDED', intro: 'The individual moments that turned great seasons into lasting legacy.', icon: Crown, stats: [['PLAYER OF TOURNAMENT', '1'], ['GOLDEN BOOTS', '2'], ['MOTM', '38'], ['WORLD XI', '1']], rows: [['2022', 'PLAYER OF THE TOURNAMENT', 'FIFA WORLD CUP'], ['2024', 'EUROPEAN GOLDEN BOOT', 'UEFA CHAMPIONS LEAGUE'], ['2025', 'WORLD XI SELECTION', 'FORWARD · FIRST TEAM']] },
  ATTRIBUTES: { eyebrow: 'PLAYER PROFILE', title: 'THE NUMBERS BEHIND THE PLAYER', intro: 'A live snapshot of the traits, archetypes and progression shaping the player.', icon: Zap, stats: [['OVERALL', '91'], ['PACE', '93'], ['SHOOTING', '93'], ['PHYSICAL', '80']], rows: [['PAC', '93', 'EXPLOSIVE FIRST STEP'], ['SHO', '93', 'ELITE FINISHING'], ['DRI', '85', 'CLOSE CONTROL'], ['PHY', '80', 'POWERFUL RUNNER'], ['PAS', '54', 'DIRECT ATTACKER']] },
  TIMELINE: { eyebrow: 'CAREER TIMELINE', title: 'THE STORY SO FAR', intro: 'A chronological record of the decisions, breakthroughs and defining days.', icon: CalendarDays, stats: [['FIRST PRO GOAL', '2022'], ['BIGGEST MOVE', '2025'], ['WORLD CUP', '2022'], ['CURRENT AGE', '20']], rows: [['2025', 'THE NEXT CHAPTER', 'Manchester United complete €300M transfer'], ['2024', 'EUROPEAN NIGHT', 'Barcelona lift the Champions League'], ['2022', 'THE WORLD STAGE', 'New Zealand win the FIFA World Cup']] },
  RECORDS: { eyebrow: 'CAREER RECORDS', title: 'NUMBERS THAT STAND OUT', intro: 'The benchmarks that define an archive built for the long game.', icon: Zap, stats: [['MOST GOALS / MATCH', '7'], ['HIGHEST RATING', '10.0'], ['MOST EXPENSIVE MOVE', '€300M'], ['WORLD CUP GOALS', '7']], rows: [['GOALS', 'Most goals in a match', '7 · New Zealand vs France'], ['RATING', 'Highest match rating', '10.0 · World Cup Final'], ['TRANSFER', 'Most expensive transfer', '€300M · Manchester United']] },
  ARCHIVE: { eyebrow: 'MEDIA ARCHIVE', title: 'THE VISUAL MEMORY', intro: 'Screenshots, matchday notes and fragments from every stage of the journey.', icon: Layers3, stats: [['SCREENSHOTS', '128'], ['MATCHDAYS', '64'], ['SEASONS', '4'], ['COLLECTIONS', '8']], rows: [['MATCHDAY', 'World Cup Final · 2022', '7—2 · PLAYER OF TOURNAMENT'], ['TRANSFER', 'Old Trafford arrival · 2025', '€300M · NEW CHAPTER'], ['TROPHY', 'Champions League night · 2024', 'BARCELONA · CHAMPIONS']] },
}

export function PitchvaultPage({ page }: { page: string }) {
  const data = pageData[page] ?? pageData.CAREER
  const Icon = data.icon
  return <section className="pv-page-view" aria-labelledby="page-title">
    <div className="pv-page-hero"><div><span className="pv-eyebrow">{data.eyebrow}</span><h1 id="page-title">{data.title}</h1><p>{data.intro}</p></div><div className="pv-page-icon"><Icon /></div></div>
    <div className="pv-page-stats">{data.stats.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
    <div className="pv-page-content"><div className="pv-section-heading"><span className="pv-eyebrow">{page} INDEX</span><span className="pv-section-rule" /></div><div className="pv-page-rows">{data.rows.map(([a, b, c]) => <article key={`${a}-${b}`}><span>{a}</span><div><h2>{b}</h2><p>{c}</p></div><ArrowUpRight /></article>)}</div></div>
  </section>
}

export default PitchvaultPage
